version: "3.9"

services:
  web:
    build:
      context: ./djangoBackend
    command: gunicorn djangoBackend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./djangoBackend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./djangoBackend/.env
    depends_on:
      - db
      - redis
      - chroma
    restart: always

  db:
    image: postgres:15
    env_file:
      - ./djangoBackend/.env
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: oussama
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "5000:8000"  # Host 5000 → Chroma internal 8000
    volumes:
      - chroma_data:/data
    restart: always

  celery:
    build:
      context: ./djangoBackend
    command: celery -A djangoBackend worker --loglevel=info
    volumes:
      - ./djangoBackend:/app
    env_file:
      - ./djangoBackend/.env
    depends_on:
      - db
      - redis
    restart: always

  celery-beat:
    build:
      context: ./djangoBackend
    command: celery -A djangoBackend beat --loglevel=info
    volumes:
      - ./djangoBackend:/app
    env_file:
      - ./djangoBackend/.env
    depends_on:
      - db
      - redis
    restart: always

  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    restart: always

  chrome-node-1:
    image: selenium/node-chrome
    container_name: chrome-node-1
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    depends_on:
      - selenium-hub
    restart: always

  chrome-node-2:
    image: selenium/node-chrome
    container_name: chrome-node-2
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    depends_on:
      - selenium-hub
    restart: always

volumes:
  pgdata:
  chroma_data:
