version: "3.9"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: botforge
      POSTGRES_USER: oussama
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - botforge

  # Redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - botforge

  # ChromaDB
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - "5000:8000"
    volumes:
      - ./chroma-data:/data
    networks:
      - botforge

  # Django Backend
  backend:
    build:
      context: ./djangoBackend
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
      - chroma
    volumes:
      - ./djangoBackend:/app
    networks:
      - botforge

  # React Frontend with Nginx
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    networks:
      - botforge

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - static:/apps/backend/static

    depends_on:
      - backend
      - frontend
    networks:
      - botforge

  # Selenium Hub
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    networks:
      - botforge

  # Chrome Node 1
  chrome-node-1:
    image: selenium/node-chrome
    container_name: chrome-node-1
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    depends_on:
      - selenium-hub
    networks:
      - botforge

  # Chrome Node 2
  chrome-node-2:
    image: selenium/node-chrome
    container_name: chrome-node-2
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TRACING=false
    depends_on:
      - selenium-hub
    networks:
      - botforge

volumes:
  postgres_data:
  chroma_data:
  static:

networks:
  botforge:
    driver: bridge
