# Generated by Django 4.2.19 on 2025-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_chatbot_unique_bot_name_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to='<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
