# Generated by Django 4.2.19 on 2025-03-21 13:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_document_path_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.chatbot_directory_path),
        ),
    ]
