# Generated by Django 4.2.19 on 2025-04-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chatbot_id_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='is_deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='system_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
