# Generated by Django 4.2.19 on 2025-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatbot_is_deployed_chatbot_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='api_url',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
