# Generated by Django 4.2.19 on 2025-04-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chatbot_api_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.chatbot')),
            ],
        ),
    ]
